### ISSUE TITLE
Elapsed time stats display at top-right of session does not update

### ISSUE THREAD

**Issue by tim-seoss** [tktan/brainworkshop#1]
The elapsed time stats ("X min Y sec done today in Z sessions") at the top-right of the session screen, does not update from session to session (only if the application is quit entirely, and then restarted).

**Comment by tktan** [comment]
I've added a temporary (and ugly) hack to update the training time stats.  Please let me know if it works.  Thanks.

**Comment by tim-seoss** [comment]
That works, thanks.
